[package]
name = "meow-gui"
version = "0.1.0"
edition = "2024"
description = "Pink-themed Slint GUI for meow-injector"
build = "build.rs"

[dependencies]
slint = { version = "1.17.1", features = ["raw-window-handle-06"] }
meow-core = { path = "../meow-core" }
rfd = "0.17.2"
log = "0.4.34"
rodio = "0.22"
ureq = "3"

[build-dependencies]
slint-build = "1.17.1"

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
] }
raw-window-handle = "0.6"
